# Project: ListaDE
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = C:/Users/lucia/Desktop/listade/listade.o C:/Users/lucia/Desktop/listade/mainListaDE.o
LINKOBJ  = C:/Users/lucia/Desktop/listade/listade.o C:/Users/lucia/Desktop/listade/mainListaDE.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib"
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ListaDE.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

C:/Users/lucia/Desktop/listade/listade.o: C:/Users/lucia/Desktop/listade/listade.c
	$(CC) -c C:/Users/lucia/Desktop/listade/listade.c -o C:/Users/lucia/Desktop/listade/listade.o $(CFLAGS)

C:/Users/lucia/Desktop/listade/mainListaDE.o: C:/Users/lucia/Desktop/listade/mainListaDE.c
	$(CC) -c C:/Users/lucia/Desktop/listade/mainListaDE.c -o C:/Users/lucia/Desktop/listade/mainListaDE.o $(CFLAGS)
